import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header";
import { useTheme } from "next-themes";
import Script from "next/script";
import Head from "next/head";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Badge, Button } from "@nextui-org/react";
import { FaCartShopping } from "react-icons/fa6";
import Cart from "@/components/Cart";
import { store } from "@/redux/store";
import { Provider } from "react-redux";
import App from "./App";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Try! Explore your shoping ^^",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
        <Head>
          <script
            defer
            src="../assets/scripts/mediapipe.js"
            crossOrigin="anonymous"
          ></script>
        </Head>
        <body className={inter.className} suppressHydrationWarning={true}>
          <App>
            {children}
          </App>
        </body>
      </html>
  );
}
